# This file is machine-generated - editing it directly is not advised

julia_version = "1.12.7"
manifest_format = "2.0"
project_hash = "94361fa469aabd3fe82c22620d09957ec8943455"

[[deps.GridToPINN]]
path = "."
uuid = "2f0e040d-41ea-45d4-abd4-30a1f3628a6c"
version = "0.1.0"
